### ISSUE TITLE
图标显示不完整

### ISSUE THREAD

**Issue by Maxthos** [xurenda/h-player-web#1]
![PixPin_2024-11-22_22-23-44](https://github.com/user-attachments/assets/ab3574e9-bd17-44f1-a401-330afde5e0b2)
![PixPin_2024-11-22_22-23-56](https://github.com/user-attachments/assets/98e8b3a2-9565-4333-8cc5-756f151f8dfb)

**Comment by xurenda** [comment]
已修复，[v1.0.3](https://github.com/xurenda/enjoy-player/releases/tag/v1.0.3)
